---
abstract: 'There can be only one'
author:
  - 'David Golden <dagolden@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
  File::Spec: 0
  File::Spec::Functions: 0
  File::Temp: 0
  IO::Handle: 0
  IPC::Open3: 0
  List::Util: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300039, CPAN::Meta::Converter version 2.132620'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-MakeMaker-Highlander
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  Dist::Zilla::Plugin::MakeMaker::Highlander:
    file: lib/Dist/Zilla/Plugin/MakeMaker/Highlander.pm
    version: 0.002
requires:
  Dist::Zilla::Role::InstallTool: 0
  List::AllUtils: 0
  Moose: 2
  namespace::autoclean: 0
  perl: v5.10.0
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/dagolden/Dist-Zilla-Plugin-MakeMaker-Highlander/issues
  homepage: https://github.com/dagolden/Dist-Zilla-Plugin-MakeMaker-Highlander
  repository: https://github.com/dagolden/Dist-Zilla-Plugin-MakeMaker-Highlander.git
version: 0.002
x_authority: cpan:DAGOLDEN
